### ISSUE TITLE
Deck Optimization - Insane Time

### ISSUE THREAD

**Issue by DJScias** [MgAl2O4/FFTriadBuddy#1]
Hello there,

I've began noticing that at a certain point the "generate optimized deck" portion of the tool becomes pretty much.. Unusable due to the long generation timer (this is with Aurifort of the Three Clubs).
![image](https://user-images.githubusercontent.com/439655/61585989-fe6d4300-ab69-11e9-804e-2f540cc4d76d.png)

I know that testing out combinations, especially with a higher number of cards, is quite cumbersome mathematically but having to wait 5 hours for a deck to be optimized kind of makes the feature a bit moot or am I mistaken?

Is this intentional, or will there be optimizations for it? The program itself is, aside from this, very handy and I can't complain. Just a bit sad that parts of the program become unusable eventually.

**Comment by MgAl2O4** [comment]
Order rule is forcing checks on all possible permutations for each tested deck. While it's correct for finding best match, solver is simply not ready for such amount of work. Hacked it out for now and always assigning rare care at second slot - hope to revisit at some point after making solver better.
