### ISSUE TITLE
In simulation mode when selecting 2x Roulette, it will take 1 of them twice and ignore the other

### ISSUE THREAD

**Issue by mweggen** [MgAl2O4/FFTriadBuddy#10]
![afbeelding](https://user-images.githubusercontent.com/361046/72669355-0f234680-3a31-11ea-901e-8eed179a0058.png)
![afbeelding](https://user-images.githubusercontent.com/361046/72669357-164a5480-3a31-11ea-8c83-617fa4e649e8.png)

**Comment by MgAl2O4** [comment]
Fixed in v27
