### ISSUE TITLE
To facilitate tournament play, add an option to disable the default rules of an npc

### ISSUE THREAD

**Issue by mweggen** [MgAl2O4/FFTriadBuddy#11]

**Comment by mweggen** [comment]
For example Prideful Stag normally has Plus, but when you play a tournament game there's only 2x roulette and no plus

**Comment by MgAl2O4** [comment]
I must admit I never tried TT tournament and I didn't know about rule changes.
Found some old reddit post, is this still accurate? 
https://www.reddit.com/r/ffxiv/comments/bn279r/a_triple_triad_tournament_guide/

I'll add simple checkbox to disable npc specific rules and tournament can be set with region overrides, but having preset names if always better. Need to check in datamined spreadsheet for details too.

**Comment by mweggen** [comment]
I think they are accurate, but I've only just started a tournament so I've only see the Rowena's Cup Classic.

**Comment by MgAl2O4** [comment]
Added quick toggle for now, will do presets later today.
