### ISSUE TITLE
Fallen Ace rule not working

### ISSUE THREAD

**Issue by mweggen** [MgAl2O4/FFTriadBuddy#12]
Just played mulitple games against Hall Overseer, and I noticed that the fallen ace rule didnt get applied. (he played cards with 1 and it flipped my A card, but the simulator did not flip it)

**Comment by MgAl2O4** [comment]
It's seems to be working correctly for me, can you get logs next time it fails? (run with cmdline argument -log, log file will be created next to executable)

Maybe it's only in some specific setup or rules were overridden by tournament mode?

**Comment by mweggen** [comment]
I wasn't in tournament mode, so that's not the issue. Ill see if i can replicate it with logs on.

**Comment by MgAl2O4** [comment]
Closing for now, no repro. 
v30 will always store log file in %LocalAppData%\FFTriadBuddy\ so maybe it will help to identify issue
