### ISSUE TITLE
settings file is deleted after closing the program (v30)

### ISSUE THREAD

**Issue by mweggen** [MgAl2O4/FFTriadBuddy#13]

**Comment by MgAl2O4** [comment]
Yes, it's on purpose. I moved all saved files to %LocalAppData% path and settings will try to load from there first. No point in keeping both files.

Can you confirm that program retains all card data after reopening?
Or, go to folder %LocalAppData%\FFTriadBuddy (type that in windows explorer address bar) and verify that settings still exists there.

**Comment by mweggen** [comment]
I see the file has moved, but when i open the program it doesn't appear to load it.

**Comment by MgAl2O4** [comment]
Uh, that's bad. I'll revert changes, but I'm afraid that saved data is lost, unless you had cloud saves enabled :(

Sorry about that.

**Comment by MgAl2O4** [comment]
Reverted. Cards should be relatively easy to restore using Icons list and comparing in game screen with what program shows in "Show only owned cards" mode. 

No easy way around deleted npcs though :/ Once you fix cards, you'll see most of npcs having empty rewards (all cards owned) so 99% sure that you already defeated them and can be checked off. Unless you remember which areas / npcs where missing, it will require comparing with ingame icons.

Sorry again, I'll make sure to avoid any destructive changes in future.

**Comment by mweggen** [comment]
Haha no worries, bugs happen :)
