### ISSUE TITLE
Marcechamp Optimize Deck

### ISSUE THREAD

**Issue by mattarolla** [MgAl2O4/FFTriadBuddy#16]
Hello, FFTriadBuddy doesn't seem to want to generate a deck for me when I have Marcechamp selected as an NPC.

**Comment by mattarolla** [comment]
I have an update. It seems to not want to create a deck for Seika either. It might have to do with the Reverse rule since both of them have Reverse.

**Comment by MgAl2O4** [comment]
You're right, it is the reverse rule. 

Workaround before I update: right click on slot and lock one card in - it won't change for optimizer purposes, but will switch to different code path that is working correctly with reverse rule.

**Comment by MgAl2O4** [comment]
Fixed in v43.
