### ISSUE TITLE
Auto Scan Between Matches

### ISSUE THREAD

**Issue by PoopBalloon** [MgAl2O4/FFTriadBuddy#17]
It would be nice if I did not have to hit the "Capture" button at the start of each match. Maybe a way to adjust the auto scan timing at the end of a match?

**Comment by MgAl2O4** [comment]
I guess I could add some limited auto recovery for continuous scans. First attempts for it were clunky, but if it's limited to "mouse outside scan area", limited retry time (~30s) and assumes that board is not moved/resized from where it was on last successful scan... hm, sure, why not.

**Comment by MgAl2O4** [comment]
Added in v52.
