### ISSUE TITLE
Overlay - Borderless Windowed Broken

### ISSUE THREAD

**Issue by DJScias** [MgAl2O4/FFTriadBuddy#2]
Hello there,

Simple bug really. The new overlay (the box) doesn't seem to work with borderless windowed mode. It disappears behind it and no longer remains in the "top position".

Kind regards,
DJScias

**Comment by MgAl2O4** [comment]
Hm, tested locally and can't repro. Maybe it's OS thing? (already saw differences between win7 and win10 in screenshot capture, so how knows what else is changed)
Only change was forcing window to be maximized instead of forcing position + size, topmost attribute is still being applied. 

I'll try going back to using size, but since it doesn't repro for me, can you try following fix?
- remove maximized from overlay form (FormOverlay.Designer.cs:424)
- adding size & location change to FormOverlay.cs:60 (before UpdateOverlayLocation call):
```
            Location = Screen.PrimaryScreen.Bounds.Location;
            Size = Screen.PrimaryScreen.Bounds.Size;
```

**Comment by DJScias** [comment]
Just compiled with those changes and now I can once again see the window on top.

Small screenshot showing it.
![image](https://user-images.githubusercontent.com/439655/63219386-6155f800-c171-11e9-81ce-5ecad0721405.png)

However I then went back and re-checked without my changes and now it does work on top of the FFXIV window by itself too..

So basically for some reason the first time I tried the overlay was stuck on my second monitor and dragging it to FFXIV just made it go under it.

Weird, but it technically means your code works as-is now!

**Comment by MgAl2O4** [comment]
Huh. I'll try it out on two monitor setup on Monday then. Thanks for verifying!

**Comment by DJScias** [comment]
Hello there,

Sorry for making another post so quickly, but I managed to reproduce it again. Here's a picture of both my screens and where you can see it on the wrong screen basically (and moving it inside FFXIV is not possible).

This is without those code changes I had to do, so basically your v17 downloaded from Github.
![y7xSwf36NR](https://user-images.githubusercontent.com/439655/63219453-99aa0600-c172-11e9-880f-8861ffe22243.png)

**Comment by MgAl2O4** [comment]
I think it's just about window area for overlay: it's spawned as maxed window (or max primary screen) and moving frame around works only inside it. Moving to other monitor area means going out of bounds :( I'll adjust size to cover everything possible and/or position in the same monitor game is running.

**Comment by DJScias** [comment]
Hello there,

Been using v18 for a bit and I can't seem to reproduce it anymore. I'll continue to try it out for a bit longer and unless I find something before I go to sleep tonight I'll be closing the issue.

Thanks again for your hard work.

**Comment by DJScias** [comment]
Hello there,

I have not been able to reproduce the issue anymore. It seems to now try its best to make sure it's on top of the game window in my borderless windowed.

Closing it as it seems resolved on my end.
