### ISSUE TITLE
Possibility of support for new Draft game mode

### ISSUE THREAD

**Issue by adelpha** [MgAl2O4/FFTriadBuddy#21]
You've probably read about the new Draft game mode, but if not:

https://na.finalfantasyxiv.com/lodestone/topics/detail/230f6e0af3536f9a40654d783c8c2f1094131070#random-daaaadb078aa3defbf3c57a8c4b6cc8181b70929

I don't know whether this is really appropriate to support given that it might only be used in the PvP Open Tournament mode, but it's part of TT now anyway, and they may decide to expand it to NPCs in the future if they haven't already (I have no idea if Draft comes up in Random).

**Comment by MgAl2O4** [comment]
Yup, would be nice - check comments in #20 and maybe it can happen. 
Can imagine it's causing problems right now, as it makes known card lists (and predictions) quite useless.

**Comment by MgAl2O4** [comment]
Closing for now, as it's pvp only feature that doesn't really affect mid match solver. 
Player matches are not supported (because solver can't handle it, but let's go with: it would be unfair)
