### ISSUE TITLE
Update for 5.5 New Rules & Cards

### ISSUE THREAD

**Issue by anivay** [MgAl2O4/FFTriadBuddy#23]
Triple Triad card restrictions have been adjusted such that we can have two 4★+ cards in a deck. 
Could the tool be updated to take this into account, as well as update the card and npc list?

**Comment by MgAl2O4** [comment]
Hi,

Thanks for letting me know :)
I'm taking a break from game, which unfortunately takes away my ability to update the client and run datamining pass. If you don't mind helping with that, I can update the tool.

Steps:
0. Download latest release of dataminer from https://github.com/ufx/SaintCoinach/releases
1. Run it on your game client (update paths to match your install)

SaintCoinach.Cmd.exe "C:\Games\SquareEnix\FINAL FANTASY XIV - A Realm Reborn"

2. In SaintCoinach's console type 3 commands (second one will take long time to run)

ui 8250082999
exd
exit

3. Grab exported data (should be in SaintCoinach's folder - the one with date), zip it and upload somewhere where I can access it (google drive being easiest)

(Alternative method: sync tool's git repo, use datasource/!Start.bat to automate steps above, zip & share results from datasource/export/ )

Once I have new datamine exports, I'll update tool to include new cards, npc & deck building rule.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by anivay** [comment]
Awesome, thank you for your quick response :D Your tool is incredibly helpful ^-^

[Here's the link to the dump-to-the-dump-to-the-dump dump dump](https://drive.google.com/file/d/11VzC5aXKVvDmVJgAD0DkDRL37l4Z_WN8/view?usp=sharing)

**Comment by MgAl2O4** [comment]
Updated with new data, deck optimizer needs more work - will take care of that in next few days as time allows.
It's just a fluff feature anyway, not really needed for farming stuff.
