### ISSUE TITLE
Board types not detected - Capture problems

### ISSUE THREAD

**Issue by soccercasanova** [MgAl2O4/FFTriadBuddy#25]
For some reason, regardless of resetting local patterns, UI defaulting, resolution presets, etc., I can't seem to get this to go away. 
I tried doing F12 to get the debug to come in, but I can't seem to get that to pop up. It's been a bit since I had this working, and I have given up after updating to v48, I don't know what I did or how to fix it. (Dual monitor setup, changed from various ones, tried switching resolutions, display monitor, in game resolutions, defaults) 

I feel like I am missing something really simple. I love this amazing thing you've got here and I will be around to troubleshoot.

![image](https://user-images.githubusercontent.com/82558455/114809804-792fb600-9d70-11eb-8e34-9f0e91467a82.png)

**Comment by MgAl2O4** [comment]
I guess it's something off with pixel colors that makes it detect as a card? Try getting a debug screenshot - i think it was available through play: simulate tab > F12 > file will be saved next to executable? (going from memory on that, can be wrong).

**Comment by MgAl2O4** [comment]
Huh, closed by mistake while trying to type comment. 

Anyway, please get a source screenshot to repro issue and I'll take a look

**Comment by soccercasanova** [comment]
I am not sure what is supposed to come out of that DEBUG screen, I apologize. You need just a screenshot with the overlay?

**Comment by MgAl2O4** [comment]
Simulate > F12 > Apply rule. Pressing this button will make a debug pass on screenshot and save source image as it's read by program for best repro conditions.

Use it when board undetected cards are reported and look for screenshot-source.jpg next to executable / in tool's current folder.

**Comment by soccercasanova** [comment]
I dont know if this is what you need but...
![release-v48screenshot-markup](https://user-images.githubusercontent.com/82558455/114815066-0e37ac80-9d7b-11eb-9fe2-b08db98f77a3.png)
![release-v48screenshot-source](https://user-images.githubusercontent.com/82558455/114815072-109a0680-9d7b-11eb-9acb-13abd9d0b846.jpg)

**Comment by MgAl2O4** [comment]
Yup, this is exactly what I needed - the second one with colors is enough :)
v49 should fix issue with cards on board and hopefully won't break anything in process. 

Noticed that matching for card's digits is painfully inaccurate. I will try to go over that and improve some thing over weekend, but I may need some help with getting more screenshots to work on (not playing the game at the moment). 

Leaving issue opened for you to verify if stuff is fixed.

**Comment by anivay** [comment]
Looks to be working as normal again! Thanks for the fix
