### ISSUE TITLE
Incorrectly Detecting Cards

### ISSUE THREAD

**Issue by duncanfmiller** [MgAl2O4/FFTriadBuddy#27]
The program is detecting non-existent cards on the board1 slot, and then failing to recognize them. This has happened in matches against several NPCs, whether or not blue or red goes first. Once an actual card has been placed in that slot and is scanned, the problem resolves.

![image](https://user-images.githubusercontent.com/10487419/115136852-75aa6200-9ff0-11eb-9139-1fe446205b29.png)

![image](https://user-images.githubusercontent.com/10487419/115136833-4c89d180-9ff0-11eb-95cd-5934b07ae5f8.png)

**Comment by MgAl2O4** [comment]
Was afraid it's going to happen after touching card detection. Thanks for screenshot, I'm able to repro issue on my end :)

**Comment by MgAl2O4** [comment]
Fixed in v51, please reopen with new screenshots if that still occurs for you. 
Finally started to run batch tests on all previously reported issues, so at least won't break already known screenshots again ;)
