### ISSUE TITLE
Board Detection Failing, Manual Value Order Incorrect.

### ISSUE THREAD

**Issue by aramil31** [MgAl2O4/FFTriadBuddy#28]
On the latest version, board detection still seems to be failing on certain cards (cannot detect The Griffin card). I have gshade disabled, and have UI scaling at the correct value. Additionally, the card value input order does not correspond with the guide on the app (app lists input order as U-L-D-R, but the card values are actually being tracked as U-R-D-L).

**Comment by MgAl2O4** [comment]
Please provide screenshots showing broken state.
Can be either made with FF14 / screen capture or (ideally) by FFTriadBuddy's debug mode, so it's exactly the size and position used for detections:
1. Get game to show broken state, blue turn, no anims
2. Go to tool's Play: Simulate tab (make sure that tool's window is not obscuring triple triad's board, etc)
3. Press F12 to enter debug mode, press Apply rule 
4. Screenshot will be saved as screenshot-source-x.jpg next to tool's executable.

Not sure if I get the card order problem correctly, is the U-R-D-L order shown in Play: Simulate tab's board state list? I think that was the only place showing side numbers in UI, will check it later too.

**Comment by aramil31** [comment]
No luck with the debug mode picture, I just get an Unhandled Exception error whenever I tried that. 
![2](https://user-images.githubusercontent.com/57973667/115277686-70850a00-a0f9-11eb-91f9-64198075fc70.PNG)

This picture shows what's happening when I use the Play: Screenshot (seems it's detecting The Griffin card now, but not the board). I hit Capture once it's my turn, anims are finished, and rules are assigned.
![tt1](https://user-images.githubusercontent.com/57973667/115277889-a5915c80-a0f9-11eb-9c85-95064600229b.PNG)
)

**Comment by MgAl2O4** [comment]
No luck with second screenshot, everything is being detected correctly as far as I can tell.
Can you copy details of that crash? I'd rather have it fixed and have exact input image that was causing detection errors

**Comment by MgAl2O4** [comment]
Actually, it did detect all card presence correctly, but failed on recognizing some of card numbers => got into unknown card state.

Log snip from loading second screenshot in my test case, all local patterns removed:
```
ParseCard(blue0): 8, 8, 4, 1 => The Griffin
ParseCard(red0): 6, 3, 7, 3 => Gnath, Poroggo (needs hash check)
C:D3D0C907700EA5C830C4064280DF08A70545620D0F120521B77F9EB4D22634B5E5B736 >>  >> unknown
ParseCard(blue1): 4, 6, 6, 8 => Seeker of Solitude
ParseCard(red1): hidden, fill:100%
ParseCard(blue2): 1, 4, 8, 8 => Hilda
ParseCard(red2): 3, 8, 4, 8 => Qitian Dasheng
ParseCard(blue3): 8, 9, 1, 7 => Hancock
ParseCard(red3): hidden, fill:100%
ParseCard(blue4): 6, 10, 10, 1 => Squall Leonhart
ParseCard(red4): empty, counter:0
Parse decks: 63ms
ParseCard(board0): empty
ParseCard(board1): empty
ParseCard(board2): 4, 1, 8, 7 => Nero tol Scaeva
>> owner: Red (410 red vs 0 blue)
ParseCard(board3): empty
ParseCard(board4): empty
ParseCard(board5): empty
ParseCard(board6): empty
ParseCard(board7): empty
ParseCard(board8): empty
```

Everything seems to be in order here, just a special case of 6-3-7-3 card that is not unique and needs to be identified by image (obviously not possible after removing all local patterns)

I'm going to redo number matching this week, but before it happens, can you try scrapping all local pattern data? You'll have to teach tool again all the rules, but it should solve card matching.

**Comment by aramil31** [comment]
I tried that a few times, didn't seem to change anything. Just had me put the rules back in and then failed to recognize the same stuff.

**Comment by MgAl2O4** [comment]
Well, can't help without a repro. Getting debug screenshots fixed will be the first step, but I need to know which part crashed = callstack from exception. If exception details don't include callstack, you can use this debug build (same as v51, just compiled in debug mode)

If getting exact input image causing the problem is not possible, maybe upcoming detection changes will help, but can't give you any ETA other than maybe this week.
 
[debugBuild.zip](https://github.com/MgAl2O4/FFTriadBuddy/files/6338780/debugBuild.zip)

**Comment by aramil31** [comment]
So that debug version isn't giving me any of the issues I had earlier. Ran it against the same NPC a few times, only now it's recognizing the cards (barring the Gnath card, keeps asking if it's Gnath or Poroggo) and otherwise working correctly.

**Comment by MgAl2O4** [comment]
This is really bizarre. I don't see any difference in minigame detection other than being significantly slower (especially for deck optimizer) due to capturing performance stats. 

Keeping the issue open for now - it will get into broken state sooner or later, and by that time hopefully you'll be able to make a repro screenshot :D

Or you know, it will fix itself after number detection rework.
Glad to see it's resolved, even though I have no idea what just happened :)

**Comment by aramil31** [comment]
I'll keep using the debug version and let you know if the issue rears its head again.

**Comment by MgAl2O4** [comment]
Heads up, v52 is now live and includes detection rework I mentioned earlier. 
Please keep sending repro screenshots if it breaks again for you ❤️
