### ISSUE TITLE
5.5 Optimizer Issues

### ISSUE THREAD

**Issue by cpommiss** [MgAl2O4/FFTriadBuddy#29]
Seems the optimizer in v52 is not working properly, or needs some controls to allow/disallow for the selection of multiple high-rank cards.

Running an optimization against Indolent Imperial, for example:

In v51: 70%+ win chance
In v52: 33% win chance (draw)

I am not certain if NPCs have had their cards changed (I would doubt it though since that seems like a LOT of work for SE to have done), but I was still able to win handily against this particular NPC with a optimized deck generated by v51.

**Comment by MgAl2O4** [comment]
Interesting, I checked with random subset of cards and it seems to prioritize using same type (scion/beastman/etc...) in optimized deck with win chance at 60+

Do you mind sharing FFTriadBuddy-settings.json for exact repro? Or just the card section from it.

prev version: 20 high level cards + 30? up to 3 stars
5.5 rules: 10x 5 star (or lower) + 10 4 star (or lower) + 16 3 star or lower

Pool of weak cards was lowered, but it should still prioritize cards with type. Maybe there aren't compatible types between those 3 sets? I didn't think about this before, but having a repro is always a good thing :)

**Comment by cpommiss** [comment]
Sure thing.  This is actually my wife's settings file -- she has about 60 more cards than me, so this should be a good test set.  She was the one who showed me the win chance difference after v52, which then prompted me to log in and do my own testing.

[FFTriadBuddy-settings.zip](https://github.com/MgAl2O4/FFTriadBuddy/files/6368818/FFTriadBuddy-settings.zip)

**Comment by cpommiss** [comment]
Yeah, I have to wonder if this is a situation where having less 4/5 star cards in the deck is more successful against legacy NPCs since their decks are presumably balanced against having the old rules.  If so (and I'm assuming a lot here), you may be able to solve this by just adding a checkbox or two to artificially limit how many 4 star cards are added to the deck during optimization.

**Comment by Eorzean** [comment]
Are you misinterpreting the rule change?

Patch 5.5 Notes
Before
Three stars or less: no restriction
Four stars or higher: one only
 ex. 5:3:3:3:3

5.5 After
Three stars or less: no restriction
Four stars or higher: up to two cards
Five stars: one only
 ex. 5:4:3:3:3

In FFTriadBuddy v52, the optimization is always 5:4:1:1:1
![512](https://user-images.githubusercontent.com/83107049/115947683-415d0700-a504-11eb-8e34-ee4e197e66fb.png)

**Comment by MgAl2O4** [comment]
Fixed in v53, I may have forgotten to sort card pools after scoring them :D
