### ISSUE TITLE
Not an issue, just a suggestion!

### ISSUE THREAD

**Issue by Sapphiratelaemara** [MgAl2O4/FFTriadBuddy#3]
Hi there! Big fan of the app and you've been updating like mad the past few days so wanted to let you know it's appreciated!

One thing I that just occurred to me though is that since you already have the ability to do an overlay and it's right next door to the card hall... would you be interested in tossing in a quick indicator for the mini-cactpot? something like https://super-aardvark.github.io/yuryu/  so you can do without having to tab out and put in each number one by one?

Entirely fine if you feel like just staying on triad though! <3 Cheers!

**Comment by MgAl2O4** [comment]
Sure, why not. I'll put it on the list :)

**Comment by Sapphiratelaemara** [comment]
Awesome! <3

**Comment by MgAl2O4** [comment]
Added in v20, enjoy!
