### ISSUE TITLE
Overlay works, but no proper suggestion

### ISSUE THREAD

**Issue by Minescence** [MgAl2O4/FFTriadBuddy#30]
Whenever I do Play: Simulate the program will suggest proper moves. 
If I enter Play: Screenshot and it begins to suggest what I do then it will simply place the cards in order from top left and go right until it has gone through the whole deck.

![FFTriadBuddy_oOmL5iW49K](https://user-images.githubusercontent.com/51507768/115971023-7722df80-a546-11eb-8ff3-36b56e3cf940.png)

It will go like this, starting from 1 and going down to the next row once it fills. I was unable to take a screenshot by going into simulate and pressing f12 too, and I have to manually take a screenshot.

![FFTriadBuddy_7jEky3W5pP](https://user-images.githubusercontent.com/51507768/115971093-d7198600-a546-11eb-885b-c21e3d3caea0.png)

**Comment by MgAl2O4** [comment]
This is a fallback behavior when solver gives up. Can you upload log file for easier repro? 
It should be located in %LocalAppData%/FFTriadBuddy/ folder, file: outputLog.txt

Will investigate.

**Comment by Minescence** [comment]
[outputLog.txt](https://github.com/MgAl2O4/FFTriadBuddy/files/6370499/outputLog.txt)

**Comment by MgAl2O4** [comment]
Logs were super helpful, fixed in v54.
