### ISSUE TITLE
Struggles to detect black cards

### ISSUE THREAD

**Issue by Minescence** [MgAl2O4/FFTriadBuddy#31]
Sometimes the tool also struggles to detect black cards. Maybe there should be an adjust function so that it can be marked as greyed out in case it doesn't detect properly? At least I couldn't spot any such function. 

![ffxiv_dx11_PGaxMKOfOI](https://user-images.githubusercontent.com/51507768/115974299-e951ef00-a55b-11eb-9b70-fe84a988fbcf.png)

![ApplicationFrameHost_QUBRKScAXi](https://user-images.githubusercontent.com/51507768/115974257-c0c9f500-a55b-11eb-902a-a7211608787a.png)

**Comment by MgAl2O4** [comment]
Hmm.. that source screenshot is getting detected correctly, need to check in game. Probably another bug in overlay's logic after my recent changes to image processing flow :<

**Comment by MgAl2O4** [comment]
Fixed in v55, apparently I forgot to test Chaos rule among other things
