### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by ShadyWhite** [MgAl2O4/FFTriadBuddy#32]
This tool is amazing, but it’s a bit unfriendly to non-English client players. Would you consider adding multi-language support to it?

**Comment by MgAl2O4** [comment]
That's a fun idea, I haven't done any localization yet. Can definitely prepare support for that, but won't be able to create or verify any data.

**Comment by ShadyWhite** [comment]
> That's a fun idea, I haven't done any localization yet. Can definitely prepare support for that, but won't be able to create or verify any data.

When needed, I can help with Chinese localization.

**Comment by MgAl2O4** [comment]
That's awesome! I'll start with just super simple replace all texts (leaving numbers intact) and ping you on this thread. 

It will probably need some UI changes to accommodate for lines becoming longer/shorter in other languages, but having a template for translation allow to do work in parallel.

**Comment by MgAl2O4** [comment]
@ShadyWhite UI strings exposed, you'll need to copy loc/strings.resx and make a version with culture code
Chinese localization will be: loc/strings.zh-CN.resx ?

This is just tool's UI though in super plain form, I still need to redo datamined assets to store multiple localizations and potentially solve text length issues (when needed)

Datamining pass could be a problem too, the tool I'm using (https://github.com/ufx/SaintCoinach) mentions only English/German/French/Japanese languages. Chinese strings probably don't exist at all in that client. Maybe there is some mirror on github I can use to pull them, idk, need to redo my data formats first anyway.

**Comment by ShadyWhite** [comment]
> @ShadyWhite UI strings exposed, you'll need to copy loc/strings.resx and make a version with culture code
> Chinese localization will be: loc/strings.zh-CN.resx ?
> 
> This is just tool's UI though in super plain form, I still need to redo datamined assets to store multiple localizations and potentially solve text length issues (when needed)
> 
> Datamining pass could be a problem too, the tool I'm using (https://github.com/ufx/SaintCoinach) mentions only English/German/French/Japanese languages. Chinese strings probably don't exist at all in that client. Maybe there is some mirror on github I can use to pull them, idk, need to redo my data formats first anyway.

https://github.com/thewakingsands/ffxiv-datamining-cn (CN,Chinese,Patch v5.41)
https://github.com/Ra-Workspace/ffxiv-datamining-ko (KO,Korean,Patch v5.40.Hot-fix)

**Comment by MgAl2O4** [comment]
Added in v60.

Looks ok-ish on first glance, please let me know if there are missing locs in tool's UI. 
Game data is defaulting to English when translation is not available (re mirrors above, not at 5.55 yet)

**Comment by ShadyWhite** [comment]
> Added in v60.
> 
> Looks ok-ish on first glance, please let me know if there are missing locs in tool's UI.
> Game data is defaulting to English when translation is not available (re mirrors above, not at 5.55 yet)

Thanks for the quick update! My system language is Chinese and the locale is also Chinese, but the UI of the tool does not display in Chinese as expected. However, the game data is displayed in Chinese. Here are screenshots of the tool and logs.
![QQ截图20210605103844](https://user-images.githubusercontent.com/44015352/120877658-62784380-c5ea-11eb-8943-ceca67945451.png)
![QQ截图20210605103941](https://user-images.githubusercontent.com/44015352/120877660-64420700-c5ea-11eb-8075-d7889406354e.png)

**Comment by MgAl2O4** [comment]
Ah. I didn't notice that program now creates a dll file with localized resources. Will path it in.

**Comment by MgAl2O4** [comment]
Fixed in v62.
