### ISSUE TITLE
Language change and cant catch the screenshot till v63

### ISSUE THREAD

**Issue by MiaElroy** [MgAl2O4/FFTriadBuddy#36]
Is there any way I can change the language of the tool? My game is in EN, but the tool is in CN now [maybe cause I use the CN windows system].
btw, after I upload from v60 to v63, it can't catch the screenshot anymore. It shows that the game isn't running right now.

**Comment by MgAl2O4** [comment]
Edit FFTriadBuddy-settings.json and set "lang":"en" - I do need to make a button for it or sth.

I guess that window name matching is to blame for broken screenshots. Let me try adding a fallback with old values in case it can't find anything.

**Comment by MiaElroy** [comment]
> Edit FFTriadBuddy-settings.json and set "lang":"en" - I do need to make a button for it or sth.
> 
> I guess that window name matching is to blame for broken screenshots. Let me try adding a fallback with old values in case it can't find anything.

It works now after I set the language to EN. Maybe it can only find the CN view game when it is set in Chinese.;-;
