### ISSUE TITLE
Request: Localisations via Localisation Management Platform Website

### ISSUE THREAD

**Issue by MaikoTan** [MgAl2O4/FFTriadBuddy#37]
# Summary

Hello, MgAl2O4.
The tool you've created is an awesome tool for FFXIV triple triad playing, thank you for creating such an amazing tool!

Recently I found that you have added localisation support in it. It worked well in the CN server.

I am going to add Japanese localisation strings to it, but it is a bit painful to modify the `resx` file manually.
Thus, do you have a plan to upload this project to some localisation management platform such as [crowdin](https://crowdin.com/) or [transifex](https://www.transifex.com/), since they would provide full support for Open Source project?

Please give it your consideration!

**Comment by MgAl2O4** [comment]
I didn't know about those platforms - will definitely check it out. Thanks for bringing it up :)

**Comment by MgAl2O4** [comment]
Uploaded loc strings to crowdin's public project: [https://crowdin.com/project/fftriadbuddy](https://crowdin.com/project/fftriadbuddy)

I contacted them for open source license, so hopefully it will stay there. If not, there's 14 days of trial left ;)

**Comment by MgAl2O4** [comment]
License approved. Updated project's readme with crowdin link.
