### ISSUE TITLE
Some missing translations in the "Adjust detection" interfaces

### ISSUE THREAD

**Issue by ShadyWhite** [MgAl2O4/FFTriadBuddy#38]
As shown in the pictures:
![QQ截图20210607130835](https://user-images.githubusercontent.com/44015352/120962007-7c07bf80-c791-11eb-9df8-7e629b2c9891.png)
![QQ截图20210607125652](https://user-images.githubusercontent.com/44015352/120962010-7d38ec80-c791-11eb-8e0d-eace5a2ec13e.png)

And, I found that some icons do not correspond to the card name. For example, in this picture, the icon is "Shadowbringers Y'shtola", but the name is displayed as "Shadowbringers Urianger".
![QQ截图20210607133101](https://user-images.githubusercontent.com/44015352/120963698-9f803980-c794-11eb-8a51-c8259a984c07.png)

By the way, would you be interested in adding an "About" tab to the Tools home page? You can list Credits lists, links to your Patreon, links to the tool's repo, links to Crowdin translations, etc.

**Comment by MgAl2O4** [comment]
Thanks for report, I'll add missing localization keys. 

Y'shtola: this is worrying. Entry comes directly from loc.xml = datamined strings

  <loc type="3" id="267" de="Innozenz" en="Innocence" fr="Innocence" ja="イノセンス" cn="雅·修特拉（暗影）" ko="이노센스" />
  <loc type="3" id="268" de="Y'shtola (Shadowbringers)" en="Shadowbringers Y'shtola" fr="Y'shtola (Shadowbringers)" ja="ヤ・シュトラ（漆黒）" cn="于里昂热（暗影）" ko="야슈톨라(칠흑)" />
  <loc type="3" id="269" de="Urianger (Shadowbringers)" en="Shadowbringers Urianger" fr="Urianger (Shadowbringers)" ja="ウリエンジェ（漆黒）" cn="兰吉特" ko="위리앙제(칠흑)" />

Judging by position of ( ) in different languages, it looks like card id numbers are offset in CN source? Will investigate.

About page: actually, this is a good idea, at least for exposing translation and bug report links. Credits/contributors exist in github/crowdin projects and keeping them in sync with tool (especially translation) will be a pain.

**Comment by ShadyWhite** [comment]
> 
> Y'shtola: this is worrying. Entry comes directly from loc.xml = datamined strings
> 
> ```
>   <loc type="3" id="267" de="Innozenz" en="Innocence" fr="Innocence" ja="イノセンス" cn="雅·修特拉（暗影）" ko="이노센스" />
>   <loc type="3" id="268" de="Y'shtola (Shadowbringers)" en="Shadowbringers Y'shtola" fr="Y'shtola (Shadowbringers)" ja="ヤ・シュトラ（漆黒）" cn="于里昂热（暗影）" ko="야슈톨라(칠흑)" />
>   <loc type="3" id="269" de="Urianger (Shadowbringers)" en="Shadowbringers Urianger" fr="Urianger (Shadowbringers)" ja="ウリエンジェ（漆黒）" cn="兰吉特" ko="위리앙제(칠흑)" />
> ```
> 
> Judging by position of ( ) in different languages, it looks like card id numbers are offset in CN source? Will investigate.
> 
My guess is that because of the version difference, a new card was inserted into the middle of the list, causing the numbering of the cards behind it to change.

**Comment by MgAl2O4** [comment]
Fixed in v66, will add about page on next UI rework 
(waiting until someone wants and makes FR translations, which are most likely to break layout)
