### ISSUE TITLE
Multi Rule / Add Rules Manually to Screenshot Mode

### ISSUE THREAD

**Issue by DerrickGnC** [MgAl2O4/FFTriadBuddy#39]
On occasions when opponent has multiple rules, the software will bundle the two rules, is there a way to manually crop the captured image, or even split the image. Barring that, could we possibly get the ability to manually add a rule? Is this something that can be done?

**Comment by MgAl2O4** [comment]
Can you capture and send me a screenshot from game where rules are not separated correctly?

Currently there's no good way of adding rules manually, it should be part of reading screen data - probably easy to fix once I have source image to work on.

**Comment by DerrickGnC** [comment]
Ya, when I get it to trigger again I will take a screenshot.

**Comment by DerrickGnC** [comment]
![FFXIVscreenshot-source-1](https://user-images.githubusercontent.com/65988750/121759101-2107fc80-caf2-11eb-82d3-299042a145e2.jpg)
![FFXIVscreenshot-markup](https://user-images.githubusercontent.com/65988750/121759102-21a09300-caf2-11eb-8589-696f84d2aad7.png)
I think these should be the screenshots you need.

**Comment by MgAl2O4** [comment]
Fixed in v67.
