### ISSUE TITLE
Bug report: Screenshot mode doesn't work

### ISSUE THREAD

**Issue by Dreamwalk3r** [MgAl2O4/FFTriadBuddy#41]
I'm using borderless windowed mode, UI scale is set to 100%, dark theme is selected, npc is selected, Buddy still can't parse screenshot. Probably related either to my target bar being at the bottom instead of top or to resolution (21:9 1440p)?
Can't attach screenshot directly due to size, so adding a zip.
[FFTriadBuddyscreenshot-source-1.zip](https://github.com/MgAl2O4/FFTriadBuddy/files/6657279/FFTriadBuddyscreenshot-source-1.zip)

**Comment by MgAl2O4** [comment]
Fixed in v68, it was exactly what you said - super wide input image.
