### ISSUE TITLE
Overlay mode time out length

### ISSUE THREAD

**Issue by delolione** [MgAl2O4/FFTriadBuddy#47]
I finally got the "screenshot" mode working and it is great. However, when the overlay shows where you should put your cards, the overlay disappears far too quickly sometimes. Would it be possible to add an option to set how long it should be up before disappearing?

Thank you for making such an awesome tool.
![image](https://user-images.githubusercontent.com/28927294/124313107-05fb3c00-db36-11eb-96e6-90ef80f5c0de.png)

**Comment by MgAl2O4** [comment]
That's a good idea, i'll expose more settings with next batch of UI changes.

**Comment by MgAl2O4** [comment]
Added in v74
Info & Settings tab > marker duration: card = number of seconds to show
