### ISSUE TITLE
Can not get v74 to save/load any Settings

### ISSUE THREAD

**Issue by Jimam123** [MgAl2O4/FFTriadBuddy#48]
Since Updating to v74 everytime i close the Program it just overrides the FFTriadBuddy-settings.json with the default one and does not save any changes i did to the Settings/Cardlist.
Also if i put a json of v73 in a Folder with the v74 exe  it does not load any of the Settings in there and overrides the File if i close it.

**Comment by MgAl2O4** [comment]
Hate to say it, but "works on my machine" :<
Can you send logs (file location: %LocalAppData%/FFTriadBuddy/outputLog.txt) from v74 doing:

- start > change something like owned cards / npcs or ui settings > end
- copy log file 1
- start again > end
- copy log file 2

**Comment by Jimam123** [comment]
here you go 
[1outputLog.txt](https://github.com/MgAl2O4/FFTriadBuddy/files/6800880/1outputLog.txt)
[2outputLog.txt](https://github.com/MgAl2O4/FFTriadBuddy/files/6800881/2outputLog.txt)

**Comment by MgAl2O4** [comment]
Thanks, those were helpful. Updated to v75: skip over broken values when loading config but keep everything else + more details what happened.

Would you mind running scenario above again? And if possible, include settings.json written after first step in uploads?

**Comment by Jimam123** [comment]
[1outputLog.txt](https://github.com/MgAl2O4/FFTriadBuddy/files/6801017/1outputLog.txt)
[2outputLog.txt](https://github.com/MgAl2O4/FFTriadBuddy/files/6801022/2outputLog.txt)
[FFTriadBuddy-settings.txt](https://github.com/MgAl2O4/FFTriadBuddy/files/6801032/FFTriadBuddy-settings.txt)

**Comment by MgAl2O4** [comment]
Fixed in v76.
