### ISSUE TITLE
UI bug with v76

### ISSUE THREAD

**Issue by LeoAlvesBahia** [MgAl2O4/FFTriadBuddy#49]
After the update once I open the software the second time the UI come all giant.

Reprodution:
   1. Open the software
   2. Close the software
   3. Open the software
  
Result should be:
![image](https://user-images.githubusercontent.com/55108062/125329243-a6621500-e31b-11eb-8c70-9f2fc695a526.png)

To fix:
After open the software the second time I can go to the FFTriadBuddy-settings.json and clear the key "ui". After that the steps of reprodution are repeted and the error happen again.

**Comment by MgAl2O4** [comment]
Lol, that's amazing. Can you send me the broken settings.json to check what exactly happened? I can't repro the issue on my end.

**Comment by MgAl2O4** [comment]
Actually, never mind, I see what happened. Fix incoming.

**Comment by LeoAlvesBahia** [comment]
Was setting the JSON.
Okay, Thx! <3 love what u did here!

**Comment by MgAl2O4** [comment]
Fixed in v77
