### ISSUE TITLE
Mini Cactpot Issues

### ISSUE THREAD

**Issue by DJScias** [MgAl2O4/FFTriadBuddy#5]
Hello there,

I honestly don't know what's going on here, but I figured I'd show this so you have a clear understanding.. The bottom line is that I can't make the mini cactpot work beyond the one time it got the first number.

Here are some screenshots about the issue (non-important parts like names are blurred):
![issue 1](https://user-images.githubusercontent.com/439655/63642667-ec2f7900-c6c2-11e9-92a4-e6c1f21d2838.png)
![issue 2](https://user-images.githubusercontent.com/439655/63642669-ed60a600-c6c2-11e9-9351-7a0f548da7ae.png)

If you need more info, do let me know. I just seem to have it happen constantly as I just try out the mini cactpot.

**Comment by MgAl2O4** [comment]
Damn, and I thought I tested this before releasing. Thanks for report, fixing...

**Comment by MgAl2O4** [comment]
Should be fixed now - tested in game this time. Leaving issue open in case it's not.

**Comment by DJScias** [comment]
Hello there,

Can confirm this now seems to work, have no other issues. And if you've tested it IG as well then I don't see why there should be more issues. :)

Thanks again for fixing it, you're doing great.
