### ISSUE TITLE
Win Chance does NOT Update

### ISSUE THREAD

**Issue by DiggityMan420** [MgAl2O4/FFTriadBuddy#50]
does not update Win chance % on setup screen. if you optimize deck to a NPC the win Chance doesn't update but if you click to add that optimized deck to Favs the win chance is there. Look at [Pic](https://imgshare.io/image/triptriad.phOLte)

**Comment by DiggityMan420** [comment]
doesnt update on Play:simulate either

**Comment by MgAl2O4** [comment]
Fixed in v78
