### ISSUE TITLE
Not saving cards

### ISSUE THREAD

**Issue by DiggityMan420** [MgAl2O4/FFTriadBuddy#51]
Every time since 76+ you make a new one the cards are resetting and not saving even with save to google.

**Comment by MgAl2O4** [comment]
Oof, that's super bad. Sorry, didn't notice it :/

**Comment by MgAl2O4** [comment]
Fixed in v79, hopefully this will be last reset of saved data.

**Comment by MgAl2O4** [comment]
Hm, just ran a quick check and it did save cards correctly for me. Can you please run a following test:

1. Save existing FFTriadBuddy-settings.json as test0.txt
2. Open program, changed something with owned cards, close program
3. Save FFTriadBuddy-settings.json as test1.txt
4. Save logs (located in: %LocalAppData%/FFTriadBuddy/outputLog.txt) as test2.txt
5. Open program again and close without any changes
6. Save logs as test3.txt
7. Zip & upload test files here.

Sorry about all the bugs, I kind of rushed UI changes without good testing first and now it's taking its toll on everyone :(

**Comment by miorioff** [comment]
[test0123.zip](https://github.com/MgAl2O4/FFTriadBuddy/files/6809947/test0123.zip)
There it is
Thanks for responding, i actually love new update, because "capture" actually works for me now (i couldn't make it to work before and kinda gave up)

**Comment by DiggityMan420** [comment]
Works fine for me now thanks

**Comment by miorioff** [comment]
New update works for me as well, thank you very much!
