### ISSUE TITLE
Request Export/Import Card list

### ISSUE THREAD

**Issue by DiggityMan420** [MgAl2O4/FFTriadBuddy#52]
You should make an export card list and import card list for the times when the card list gets cleared do to some unknown reason. Google is good but hard copy is better

**Comment by DiggityMan420** [comment]
i see you have a way to debug it I read but a button would be nice for those not to inclined to coding

**Comment by MgAl2O4** [comment]
Google save was mostly for me keeping settings in sync between work and home PC :P
I like the explicit export idea, will add that in.

**Comment by DiggityMan420** [comment]
and  import

**Comment by MgAl2O4** [comment]
Added in v81
