### ISSUE TITLE
Glitching buttons, links, etc.

### ISSUE THREAD

**Issue by Zarbalan** [MgAl2O4/FFTriadBuddy#53]
Hi there,

sadly i don't know how i should describe my problem better than what i wrote in the title. When i hover over any clickable object in the program with my mouse it will glitch/disappear/reappear etc. - maybe you know something about this strange behaviour?

Regards,

Daniel

![Bild_2021-07-13_180937](https://user-images.githubusercontent.com/52489372/125487088-18997ab2-a276-4c8c-8c5b-0ac55c8caeca.png)

**Comment by MgAl2O4** [comment]
Only thing that comes to mind is some windows accessibility setting messing up hover style.
Do you know if you're using anything like that?

I can see that buttons and comboboxes for region rules are affected, does it happen on tabs (Setup, Play, Cards, etc..) too?

**Comment by Zarbalan** [comment]
Aye, when i'm hovering over any clickable object it will glitch in some way or another. :(

**Comment by Zarbalan** [comment]
Version 73 works fine, i guess it is  .NET Framework 4.8 related? With v74 the problem starts to occur. I have installed the new framework with the last windows update... i even thought about that as a problem and deinstalled + reinstalled the framework update without any luck on solving the issue...

**Comment by MgAl2O4** [comment]
I found some similar looking issues reported for that UI framework: https://github.com/dotnet/wpf/issues/707
Last comments mention is being possibly caused by some 3rd party program? (Nahimic? Realtek? Sonic Studio?)

.net 4.8 is probably not the reason, but switching to WPF UI. I'll prep a few small programs for you to test and maybe pinpoint the issue here :/

**Comment by Zarbalan** [comment]
Yeah, that would be nice - i guess it could be sonic studio + nahmic related. I had an error occuring while the last update of sonic studio was installed (NahimicSvc32.exe was involved as far as i remember) - but i deinstalled every piece of realtek, sonic studio, nahimic which i could find in my software - sadly the error remains.

**Comment by MgAl2O4** [comment]
[WPF-test.zip](https://github.com/MgAl2O4/FFTriadBuddy/files/6810777/WPF-test.zip)

3 simple test programs:

- .net 4.7, default hover behavior
- .net 4.8, no hover behavior
- .net 5.0 (win 10 only!), default hover behavior

Can you check if any of those works correctly for you? It's all just a window with a button that does nothing.

Just in case, source code of all 3: 
[WPF-test-sourcecode.zip](https://github.com/MgAl2O4/FFTriadBuddy/files/6810794/WPF-test-sourcecode.zip)

**Comment by Zarbalan** [comment]
default-4.7.exe makes the text bigger on hovering over the button.
default-core.exe points me to https://dotnet.microsoft.com/download/dotnet/5.0/runtime because of having an on version of .net core installed
and nohover.exe opens and when i am hovering over the button, nothing happens.

**Comment by MgAl2O4** [comment]
Hm, let me prepare another batch of 4.8 tests then, maybe there is a way to completely kill visual styles and have it working correctly...

**Comment by MgAl2O4** [comment]
[WPF-test2.zip](https://github.com/MgAl2O4/FFTriadBuddy/files/6810976/WPF-test2.zip)

Expected on screen:
![image](https://user-images.githubusercontent.com/51430403/125501551-0cd79135-1034-45ac-903b-0e6edfbfff5c.png)

**Comment by Zarbalan** [comment]
I went through all points on this reddit thread https://www.reddit.com/r/MSI_Gaming/comments/l45fnj/guide_how_to_uninstall_nahimic_completely_from/ and it worked for me. Thx to your dedication and the hunch about the nahimic thing it works fine now. :D
I appreciate your hard work and help! ♥

**Comment by MgAl2O4** [comment]
Glad to hear it's working for you, stupid windows and their stupid UI grumble grumble :D

**Comment by Zarbalan** [comment]
Now, with the problem solved - how can i honor your commitment? Do you have a patreon, kofi, whatever? ^^

**Comment by MgAl2O4** [comment]
Please don't :)
It's just my pet project that I love messing with. I don't want to create expectation that features or support comes at a price. I appreciate the gesture though.
