### ISSUE TITLE
Problem with capture (Play: Screenshot)

### ISSUE THREAD

**Issue by Zarbalan** [MgAl2O4/FFTriadBuddy#54]
Hello,

me again with a faulty behaviour i do not find in the solved error section.
When i'm playing with capture and the program doesn't recognize a card i can manually adjust it - so far so good - but when i'm clicking capture again the manually adjusted card won't stay adjusted and isn't recognized again.
Any hints how to solve this problem?

Regards,

Daniel

**Comment by MgAl2O4** [comment]
Either it failed to determine exact position of numbers to parse or i messed up saving custom patterns. 

Please send a screenshot (regular or with F12 > apply) showing the issue (unobstructed mini game on screen when it fails to recognize card) - this type of bug needs a repro to fix

**Comment by Zarbalan** [comment]
Send you a mail with the screenshot.

**Comment by MgAl2O4** [comment]
Fixed in v82.
