### ISSUE TITLE
Doesn’t work for "same" rule 

### ISSUE THREAD

**Issue by SuperLargeEggplant** [MgAl2O4/FFTriadBuddy#55]
I apologize for my poor English at the beginning.

This rule is same and Order. Look at the 4th and 5th pictures.
”Qitian Dasgeng” in the middle turns left and right according to Same rule and turn the card below according to the normal rule.
Originally, the lower left and lower right should not be turned over by the combo.

so this match is a draw, not a win.

1
![image](https://user-images.githubusercontent.com/87522691/125924039-39c76439-4eea-4b29-b8ae-2c667711d6df.png)
2
![image](https://user-images.githubusercontent.com/87522691/125924066-37521e92-eb85-49c5-84fc-98cb87ae670f.png)
3
![image](https://user-images.githubusercontent.com/87522691/125924086-eaf9f2bf-ab71-4fb8-89c9-940b4a38c17e.png)
4
![image](https://user-images.githubusercontent.com/87522691/125924163-b3d33983-1885-4fac-a650-7342837a8f63.png)
5
![image](https://user-images.githubusercontent.com/87522691/125924180-1cc4cf8f-6e2b-497f-a1aa-0b8f6f3bbdaf.png)

**Comment by MgAl2O4** [comment]
Thanks for the report, will get it fixed.

Do you know if combo chain can proc another plus / same? Or it is always same/plus > combo > combo > final state

**Comment by MgAl2O4** [comment]
Fixed in v83.

**Comment by SuperLargeEggplant** [comment]
I think that Same / Plus will be activated only at the beginning of the combo logic.
(If it's not a question with that intention, it's because my poor English. )

Thx for the quick fix.
