### ISSUE TITLE
not showing correct cards

### ISSUE THREAD

**Issue by DiggityMan420** [MgAl2O4/FFTriadBuddy#56]
not showing correct cards after optimize deck to play simulate see [PIC](https://imgshare.io/image/pqPL9e)

**Comment by MgAl2O4** [comment]
Does it fix itself after selecting anything and restarting simulation game?

**Comment by DiggityMan420** [comment]
even if it does u cant pick a swap

**Comment by DiggityMan420** [comment]
no it puts the cards down below

**Comment by DiggityMan420** [comment]
i have to save to fav and restart app

**Comment by MgAl2O4** [comment]
Fixed in v84

**Comment by DiggityMan420** [comment]
ty for your fast fixes
