### ISSUE TITLE
Suggestion: Option for "Always On Top"

### ISSUE THREAD

**Issue by johnennion** [MgAl2O4/FFTriadBuddy#57]
This is a fantastic tool, thank you so much for creating it.

As I play in 4K and with a non-standard set-up, I can't use the "screenshot" mode of the tool. Would it be possible to have an option to turn on always on top so I can use the simulator without tabbing while I am in borderless windowed mode?

Thanks again.

**Comment by MgAl2O4** [comment]
Sure thing, always happy to help with QoL changes.

Would you mind sending a screenshot showing minigame on screen that can't be detected correctly anyway? Fixing that would be more beneficial (although probably take longer to get done)

**Comment by MgAl2O4** [comment]
added in v85

**Comment by johnennion** [comment]
ty this rules - will look for that screenshot
