### ISSUE TITLE
Spanish translate?

### ISSUE THREAD

**Issue by Darkloud91** [MgAl2O4/FFTriadBuddy#58]
can open a Spanish translate? i wanna help.

**Comment by MgAl2O4** [comment]
Sure thing, I added Spanish to languages on crowdin project (https://crowdin.com/project/fftriadbuddy)

Just to be clear, this will cover only tool's UI. Things like names of cards, npcs, rules, tournaments or locations in game come from data mining of game client and are not really exposed for translations

**Comment by Darkloud91** [comment]
> Sure thing, I added Spanish to languages on crowdin project (https://crowdin.com/project/fftriadbuddy)
> 
> Just to be clear, this will cover only tool's UI. Things like names of cards, npcs, rules, tournaments or locations in game come from data mining of game client and are not really exposed for translations

yeah i know. Thanks so much ^^

**Comment by MgAl2O4** [comment]
Added in v86 using current state of translation (wow, half way there already, nice!)
will be updating again once there are more entries completed
