### ISSUE TITLE
Suggestion: Update Cards to new HD Icons

### ISSUE THREAD

**Issue by ibigfire** [MgAl2O4/FFTriadBuddy#63]
Hiya!  Totally just a suggestion, but now that FFXIV has implemented a new HD icons mode I think it'd be swell if the program was updated to match, would make the cards look a lot nicer in the program.

Totally not a big deal though, just a suggestion for if you feel like it.  Cheers, and thanks for the program, regardless!

**Comment by MgAl2O4** [comment]
I can update to match, but don't know where to get icons from. Datamining tool (SaintCoinach) finds only two types of triple triad images:
- 40x40 card icons (id: 82500+)
- 104x128 card images with frame (id: id: 82100+)

Do you know how to access hd stuff?

**Comment by MgAl2O4** [comment]
Welp, added big card images for now in v90
Let me know if there's still a reason to investigate hd icons, preferably with info how to access them ;)

**Comment by ibigfire** [comment]
I've been trying to find them in Textools for exporting or the like but it's been difficult for sure.  This update with the bigger cards has made a big difference in their readability though to make it easier to set up the deck for each new NPC, so that might be good as is.  Thanks for implementing it!
