### ISSUE TITLE
Left click & Right click on card image displays incorrect card name 

### ISSUE THREAD

**Issue by althaiaDev** [MgAl2O4/FFTriadBuddy#66]
Diamond weapon stats in the app: (TOP, RIGHT, BOTTOM, LEFT) 1, 9, 7, 8. 
Diamond weapon stats in the game: (TOP, RIGHT, BOTTOM, LEFT) 9, 8, 7, 1.
![image](https://user-images.githubusercontent.com/86332727/128721554-4aba59a7-deea-40df-9e7e-e51576030d3a.png)

**Comment by althaiaDev** [comment]
I looked in the card list and it looks like the info is accurate there, but the info displayed doesn't look right when running the app?

`<card id="324" icon="082824.png" rarity="3" type="4" up="9" lt="8" dn="7" rt="1" sort="307" group="0" />`

**Comment by MgAl2O4** [comment]
![test1](https://user-images.githubusercontent.com/51430403/128722446-a7aa588c-9fa9-4770-8467-0f258ffa4168.png)

Looks correct for me, image you pasted is a bismarck card. Maybe localization names are not matching - which language are you using?

**Comment by althaiaDev** [comment]
Wow im so sorry, i'm so out of it. I was wondering why the image looked weird... When i click on it, it says "The Diamond Weapon", which is why i got confused. I am just using english, and this is an auto generated deck using the "Optimize deck for NPC" option.

![image](https://user-images.githubusercontent.com/86332727/128722723-dc66fe3f-680b-4837-9a31-7b4f9d1ddcd3.png)

**Comment by althaiaDev** [comment]
Oh, it seems this is likely just user error... when i click on all the cards it shows "Diamond weapon"... So i may not be understanding the reason the popup shows up. 

![image](https://user-images.githubusercontent.com/86332727/128722922-54b905fe-b725-49bf-9e57-311dc887ad42.png)

**Comment by MgAl2O4** [comment]
Oh fun, this bug again :<
Please check right click on cards, it should be accurate. Left click is uh, usually working, but apparently it still manages to break itself from time to time. I'll look into this.

**Comment by althaiaDev** [comment]
Both right click and left click are showing diamond weapon. Would you like me to close this issue or should i retitle/update the top comment?

**Comment by MgAl2O4** [comment]
Meh, doesn't matter. Can you send me logs? I can't repro any issues with using deck optimizer and card selection menu.
It's written to %localappdata%/FFTriadBuddy/outputLog.txt

**Comment by althaiaDev** [comment]
[outputLog.txt](https://github.com/MgAl2O4/FFTriadBuddy/files/6955190/outputLog.txt)
Here you go :)

**Comment by MgAl2O4** [comment]
Guess fix in v91. Still no idea what's causing it, wasn't able to find any clues in log file :(

**Comment by MgAl2O4** [comment]
(closing issue for tracking, feel free to reopen if still broken)
