### ISSUE TITLE
how to change to red side?

### ISSUE THREAD

**Issue by vegas2k** [MgAl2O4/FFTriadBuddy#76]
Maybe I just don't see it.  I have v98.  I cant' see how to play from the red player side.  thanks!

**Comment by MgAl2O4** [comment]
You don't.

This solver is designed to work only with card pools of regular NPCs and is not capable of running pvp / tournament NPC match. There is an option to switch to tournament rule set (added mostly for experimenting), but solver still simulates pve version of NPC and all suggestions will be based on incorrect cards = wrong. 

And before you ask: no, I currently don't have any plans of adding that.
