### ISSUE TITLE
Reverse + Fallen Ace not working correctly

### ISSUE THREAD

**Issue by emerald000** [MgAl2O4/FFTriadBuddy#79]
![ffxiv_dx11_kviBHbCzsm](https://user-images.githubusercontent.com/4655664/186908577-581548a0-b27e-4bf0-beb0-39b63f127bc1.png)

Triad Buddy thinks the only move ends in a draw, while it is actually a win. The Ultima, the High Seraph (right A) flips the Chocobo (left 1) due to Fallen Ace.

**Comment by MgAl2O4** [comment]
Thanks for report, will be fixed in plugin version 1.7.0.2
