### ISSUE TITLE
About the "chaos" mode

### ISSUE THREAD

**Issue by renyanpeng** [MgAl2O4/FFTriadBuddy#85]
Is it possible to let the players use the cards themselves after the system randomly selecting them?

**Comment by MgAl2O4** [comment]
I'm not sure what do you mean. 

- play: screenshot => should be auto detected already and always show forced card as next move
- play: simulate => you can adjust forced blue/player card with selector in bottom left corner (see attached image)
- dalamud plugin version => same as screenshot mode, forced card should be auto detected

If this is about forced card not recognized correctly (screenshot / dalamud plugin), I'll need more details on how to repro.

![snap](https://github.com/MgAl2O4/FFTriadBuddy/assets/51430403/d756aace-02d0-4008-8354-2acfc77b631c)

**Comment by renyanpeng** [comment]
I see, thanks :)
