### ISSUE TITLE
Reverse + Plus rules claim card it should not

### ISSUE THREAD

**Issue by tyhindmarsh** [MgAl2O4/FFTriadBuddy#86]
Issue:
Simulator claims red card is converted to blue through a plus combo when it should not as it doesn't take into consideration reverse.

Steps to re-create:
My deck:
1. Magitek Death Claw
2. Gaelicat
3. Moogle
4. Sabotender
5. Ahriman

NPC: Marcechamp
1. Red plays Amalj'aa on tile C3
2. Simulator recommends blue Magitek Death Claw on tile A3
3. Red plays Gaelicat on A2, (Magitek Death Claw >> Red)
4. Simulator recommends blue Moogle on tile B3 (Amalj'aa >> Blue, Magitek Death Claw >> Blue, **Gaelicat >> Blue** (this last swap is incorrect)
Simulator:
![image](https://github.com/MgAl2O4/FFTriadBuddy/assets/61497179/6b2ddd7f-41c9-4e70-b816-5c883f85507a)

In game: (1 star moogle was blue before NPC placed 3 star moogle. Gaelicat was never swapped to blue)
![image](https://github.com/MgAl2O4/FFTriadBuddy/assets/61497179/c5473f11-5857-457b-839c-7081cfbaa6ec)

Possible cause:
In this bIsCaptured check here to see if blue Magitek Death Claw takes red Gaelicat in combo, it is checking if 3 > 1 (Magitek left side > Gaelicat right side), so it is set to true. Since the combo counter is 1 at this point, allowMods is false so reverse is never checked as a modifier in the if statement on line 287 so it instead jumps straight to capturing the card.
https://github.com/MgAl2O4/FFTriadBuddy/blob/b50911a64e912bfa953c45eb86035b60d0cfe51a/sources/gamelogic/TriadGameSimulation.cs#L286-L301

**Comment by MgAl2O4** [comment]
Found this today when going over github, thanks for very detailed repro and analysis!

Modifiers were turned off on purpose during combo captures, as it usually uses normal rules when doing chains (iirc). Apparently I was mistaken and at least reverse is still in effect. Will update capture logic to exclude it.
