### ISSUE TITLE
Cards added after 6.5?? When?

### ISSUE THREAD

**Issue by Youtsax** [MgAl2O4/FFTriadBuddy#87]
Hii. I love this simulator, it really helps, even if i play on console. But i do wonder, i see it hasn't been updated since oct-23. Is it any plans to update it soon to include cards added after 6.5 (oct-23)? SInce there's been quite a few cards added since then :) Thank you for everything you do! I didn't know where to post this, if i should've sent an email or somthing so. I'm trying

i cant use the dalamud plugin since im on ps5 so id love for this to be updated if possible...

**Comment by MgAl2O4** [comment]
Thanks for reminder, it's updated now.
